-- 코드를 입력하세요
SELECT A.PRODUCT_ID, PRODUCT_NAME, AMOUNT * PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN "2022-05-01 00:00:00" AND "2022-05-31 23:59:59"
    GROUP BY PRODUCT_ID
) B ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID ASC;