-- 코드를 입력하세요
SELECT A.APNT_NO, C.PT_NAME, A.PT_NO, A.MCDP_CD, B.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
JOIN DOCTOR B ON A.MDDR_ID = B.DR_ID
JOIN PATIENT C ON A.PT_NO = C.PT_NO
WHERE DATEDIFF(APNT_YMD, "2022-04-13") = 0 AND APNT_CNCL_YMD IS NULL AND A.MCDP_CD = "CS"
ORDER BY APNT_YMD ASC;