-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN 
    (SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5) B 
ON A.CAR_ID = B.CAR_ID
WHERE MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY MONTH, CAR_ID
ORDER BY
    MONTH ASC,
    A.CAR_ID DESC;