-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY = "과자" OR CATEGORY = "김치" OR CATEGORY = "국" OR CATEGORY = "식용유"
    GROUP BY CATEGORY
) B ON A.CATEGORY = B.CATEGORY AND A.PRICE = B.PRICE
ORDER BY MAX_PRICE DESC;